---
- name: add Group for rport
  ansible.builtin.group:
    name: "{{ rport_group }}"
    state: present
  tags:
    - client

- name: Add User for rport
  ansible.builtin.user:
    name: "{{ rport_user }}"
    shell: /bin/bash
    groups: "{{ rport_group }}"
    state: present
    comment: User rport
  tags:
    - client

- name: set sudoers
  ansible.builtin.template:
    src: rport-nopasswd.j2
    dest: /etc/sudoers.d/rport-nopasswd
    mode: 0440
    owner: root
    group: root
  tags:
    - client

- name: rport Config /etc
  ansible.builtin.file:
    path: "{{ rport_config_path }}"
    owner: root
    group: root
    mode: 0655
    state: directory
  tags:
    - client

- name: rport Config/Log Path
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ rport_user }}"
    group: "{{ rport_group }}"
    mode: 0755
    state: directory
  with_items:
    - "{{ rport_log_path }}"
    - "{{ rport_data_dir }}"
  tags:
    - client

- name: set Template
  ansible.builtin.template:
    src: rport.conf.j2
    dest: "{{ rport_config_path }}/rport.conf"
    owner: "{{ rport_user }}"
    group: "{{ rport_group }}"
    mode: 0655
  notify: restartRport
  tags:
    - client

- name: set service rport
  ansible.builtin.template:
    src: systemd_rport.service.j2
    dest: /etc/systemd/system/rport.service
    owner: root
    group: root
    mode: 0644
  notify: restartRport
  tags:
    - client

- name: systemd rport
  ansible.builtin.systemd:
    name: rport.service
    state: started
    enabled: true

...
